### ISSUE TITLE
Update meetup.com API to oauth

### ISSUE THREAD

**Issue by riasvdv** [fullstackbelgium/fullstackbelgium.be#30]
https://www.meetup.com/meetup_api/auth/?utm_medium=email&utm_source=transactional&utm_campaign=api_update&utm_content=en_06142019

**Comment by riasvdv** [comment]
I think we need this one https://www.meetup.com/meetup_api/auth/#oauth2servercredentials but can't seem to make it work. Do we have a pro membership?

**Comment by driesvints** [comment]
@riasvdv no. Urgh, what a mess.

**Comment by riasvdv** [comment]
> This is a reminder that Meetup is changing its API access and that you have until August 15, 2019 to update your integration

**Comment by riasvdv** [comment]
Thanks to https://www.tomasvotruba.cz/blog/2019/06/17/how-to-upgrade-meetup-com-api-to-oauth2-with-guzzle/ it was a lot easier to implement than I thought
