### ISSUE TITLE
Add some analytics?

### ISSUE THREAD

**Issue by riasvdv** [fullstackbelgium/fullstackbelgium.be#31]

**Comment by driesvints** [comment]
Hmm I thought we had analytics on the previous one. Maybe they were never added to the new design. Can you check in the git history of the previous version is there was a google analytics set up?

**Comment by riasvdv** [comment]
Nope, none in the history either

**Comment by driesvints** [comment]
@riasvdv I've added you to the Analytics account of FSBE
