### ISSUE TITLE
Switch to NPM for package management

### ISSUE THREAD

**Issue by driesvints** [fullstackbelgium/fullstackbelgium.be#32]
If it's ok with you @riasvdv I'd like to switch to NPM for managing front-end dependencies. I've stopped using Yarn for all other projects and think this is the only one left. I accidentally used NPM the last time I did an update 🤭 (but without any consequences luckily).

Think the only thing we need to do is do a one time install to have a package-lock.json file and remove the yarn.lock file. Also update the deploy script.

**Comment by riasvdv** [comment]
I have no real preference, added a `package-lock.json` and changed the deploy script to use `npm ci`
