### ISSUE TITLE
Add some call to actions on homepage

### ISSUE THREAD

**Issue by driesvints** [fullstackbelgium/fullstackbelgium.be#46]
Currently it's not entirely clear on how to get to the venue and sponsor sections. Let's add some buttons on the top intro part that say: "Host an event" & "Sponsor us". Maybe underneath the speaker parts. Let's add buttons so there's clear CTA's.

**Comment by riasvdv** [comment]
Maybe it could be nice to also show the sponsor logo on the homepage of the next meetup, could be an extra incentive

**Comment by driesvints** [comment]
@riasvdv you mean on our website? Yeah we could do that

**Comment by driesvints** [comment]
@riasvdv maybe make a separate issue for that
