### ISSUE TITLE
Talk slots sometimes have line break issues

### ISSUE THREAD

**Issue by driesvints** [fullstackbelgium/fullstackbelgium.be#5]
When I tried adding the second talk slot for https://www.meetup.com/fullstackantwerp/events/vtkdppyzdbkc/ it didn't had any line breaks on the meetup.com event even though it did in the textarea field in Nova. I first copy/pasted the content from the 1st talk slot textarea into the 2nd talk slot textarea and then adjusted the content a bit before I published it.

**Comment by freekmurze** [comment]
Fixed!

**Comment by driesvints** [comment]
Still seems to be an issue.

![screen shot 2019-01-24 at 16 32 37](https://user-images.githubusercontent.com/594614/51688777-95ab7080-1ff5-11e9-969f-3055a69a3c98.png)

**Comment by freekmurze** [comment]
Does not seem to have anything to do with speaker 2 per sé.

I removed and re-added all linebreaks, and than it just worked

My thinking is that the content was copied pasted from somewhere and contained a weird character.
