### ISSUE TITLE
Event time keeps resetting

### ISSUE THREAD

**Issue by driesvints** [fullstackbelgium/fullstackbelgium.be#6]
For some reason the event time keeps resetting to the moment the event was updated and thus the date on meetup.com is changes. Maybe related to this change: https://github.com/fullstackbelgium/fullstackbelgium.be/commit/b577effd0318bf90e87e21ca5615674d1b0f0398

The event below is for February but now has a confusing January in its name:

![screen shot 2019-01-28 at 18 57 33](https://user-images.githubusercontent.com/594614/51855925-b09c1e80-232e-11e9-9e27-1bf420f31d1d.png)

**Comment by freekmurze** [comment]
Can't reproduce this.

Tried this:
1. opened up the event at Rombit
2. added a 🍕 emjoi
3. saved
4. opened up the event on meetup and saw the title is still "February"

Can you provide steps to reproduce @driesvints

**Comment by driesvints** [comment]
I can't reproduce it anymore. It happens sporadically. I'll monitor and try to add the steps if it happens again.

**Comment by driesvints** [comment]
Just experienced this again with https://fullstackbelgium.be/nova/resources/events/3

Steps:

- I entered the venue info
- Clicked "Update Event"
- Date changed to today/current timestamp

Here's a screenshot which shows that the time was changed to a few moments before I posted this comment:

![screen shot 2019-02-07 at 14 59 11](https://user-images.githubusercontent.com/594614/52416081-0ae46e80-2ae9-11e9-9e0d-ab55815e9faf.png)

**Comment by driesvints** [comment]
Fyi: I changed the time again so people on meetup.com aren't confused.

**Comment by freekmurze** [comment]
Event time removed.
